Draft proposal of updated IErrorReporter interface
sujeffreyl/libpalaso pull request #1
Opened 2022-04-21 19:34 UTC by sujeffreyl

2022-04-21 20:59 UTC, JohnThomson requested changes
I think you're on a reasonable track for handling the cases where we really need to show multiple buttons and wait for a response., though I've called attention to a few problems. But I really want to retain the idea that exception-reporting is fire-and-forget (that is, the thread that reports the error is not kept waiting for the user).

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core.Desktop/IO/FileUtils.cs
> +			// TODO: Customizing of the 1st button is not implemented yet, don't check in until you deal with this.
Comment is out of date

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core/Reporting/ErrorReport.cs
> +		void NotifyUserOfProblem(IRepeatNoticePolicy policy, Exception error, string message, string[] actionLabels, EventHandler<string> selectionHandler);
This feels error-prone. Very likely the labels should be localized. But very likely the tests in the selectionHandler will be written based on the English labels, which will fail if some other locale is in use.
Maybe actionLabels could be an array of objects each having an id and a label, and the id is what gets passed to selectionHandler? Or selectionHandler could be passed the index of the button?

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core/Reporting/ErrorReport.cs
> +
In dealing with the tricky case 5, we seem to have lost track of what we wanted to do about the overloads that report an exception but do NOT give their callers a configurable button. We wanted a 'fire-and-forget' method in this API that leaves it entirely up to the implementor whether to offer a way to report the exception (but does give them the exception just in case). This method would be expected to return quickly, without waiting for user interaction.

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Windows.Forms/Reporting/WinFormsErrorReporter.cs
> +		protected void NotifyUserOfProblem(IRepeatNoticePolicy policy,
Looks like you didn't finish updating this.

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Windows.Forms/Reporting/WinFormsErrorReporter.cs
> +			string alternateButtonLabel = actionLabels.Length >= 2 ? actionLabels[1] : null;
If you're not actually going to implement support for more buttons here, seems like you should Debug.Assert or throw if you get them.

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core/Reporting/ErrorReport.cs
>  		void ReportNonFatalException(Exception exception, IRepeatNoticePolicy policy);
As long as we're redesigning here...I wonder whether having a repeat notice policy makes any sense? This method is called because there are multiple things the user might reasonably do in response to the problem and we need the user to make a choice. Why would we not want the message to appear always?

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core/Reporting/ErrorReport.cs
>  		void ReportNonFatalExceptionWithMessage(Exception error, string message, params object[] args);
One more think I don't like here, though I'm not sure what to do about it. It looks like a fire-and-forget error reporter, where the caller might expect it to return immediately and the handler to be called later, possibly on another thread. But it's not: whatever buttons you pass, or presumably even if you don't pass any, it will not return until the user clicks a button. Maybe a boolean argument waitForResponse would be a useful addition?

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core/Reporting/ErrorReport.cs
>  		void ReportNonFatalMessageWithStackTrace(string message, params object[] args);
Let's not use EventHandler here. That is specific to things that are declared as Events. I think it would be better to use an Action<string>. You could also consider a Func<bool, string> where the bool would indicate whether to close the dialog after calling the handler. (e.g., a Details or Help button might show some more information, but should not close the dialog until the user clicks another button). (You see where designing something like this without lots of examples of uses is hard?)

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core.Desktop/IO/FileUtils.cs
> +					throw error; // pass it up to the caller
This is somewhat problematic. We're going to throw this exception INSIDE the configurable, third-party exception handler. What if that handler is set up to catch exceptions and report "error handling failed"? I think it would be better that this handler sets a flag which causes the exception to be rethrown AFTER NotifyUserOfProblem returns.

2022-04-21 20:59 UTC, JohnThomson commented on SIL.Core.Desktop/IO/FileUtils.cs
> +					throw error; // pass it up to the caller
It's also very likely that throwing the exception at this point will mess up closing down the error dialog.

2022-04-21 22:27 UTC, sujeffreyl commented on SIL.Core/Reporting/ErrorReport.cs
> +		void NotifyUserOfProblem(IRepeatNoticePolicy policy, Exception error, string message, string[] actionLabels, EventHandler<string> selectionHandler);
Yeah, this is a tricky topic that I was trying to figure out. Here are some thoughts i have:

- I'm pretty sure that the current "Give Up" button is not localized.
- I'm kinda surprised, but I couldn't dig up the code that localizes "OK". I looked in https://github.com/sillsdev/libpalaso/blob/master/SIL.Windows.Forms/Reporting/ProblemNotificationDialog.Designer.cs and don't see it...
- My thoughts (which I did not document anywhere...) were that if the caller customizes the actionLabels, they should provide the localized button texts.

What do you think?

2022-04-21 22:33 UTC, sujeffreyl commented on SIL.Core/Reporting/ErrorReport.cs
> +
Hmm... I view Overload 3 -> Overload 4 -> new function as being sufficient for that. Since it just fills in the parameters for you. And the implementor can still do fire and forgot. I guess you don't though? I guess we'll need to talk this through more.

2022-04-21 22:33 UTC, sujeffreyl commented on SIL.Windows.Forms/Reporting/WinFormsErrorReporter.cs
> +		protected void NotifyUserOfProblem(IRepeatNoticePolicy policy,
How so?

2022-04-21 22:34 UTC, JohnThomson commented on SIL.Core/Reporting/ErrorReport.cs
> +		void NotifyUserOfProblem(IRepeatNoticePolicy policy, Exception error, string message, string[] actionLabels, EventHandler<string> selectionHandler);
I don't see a distinction between button texts and action labels, so I'm puzzled by your comment. I agree (I think) that the caller should provide localized labels. What I'm worried about is that the selectionHandler will then be passed the localized button text, and I think that's a bug waiting to happen (e.g., if the handler contains a switch with cases based on the English button texts).

2022-04-21 22:34 UTC, sujeffreyl commented on SIL.Windows.Forms/Reporting/WinFormsErrorReporter.cs
> +			string alternateButtonLabel = actionLabels.Length >= 2 ? actionLabels[1] : null;
I think the handling on lines 87-89 should cover that.

2022-04-21 22:40 UTC, sujeffreyl commented on SIL.Core/Reporting/ErrorReport.cs
> +		// actionLabels is the text of the "buttons" the implementer should use.
One awkward thing I realized is that... WinFormsErrorReporter calls the first two buttons "OK" and "Details", but I think in Bloom we use "Close" and "Report". So actually, I think I need some way to express that button labels should be their default value.

2022-04-21 22:42 UTC, sujeffreyl commented on SIL.Core.Desktop/IO/FileUtils.cs
> +					throw error; // pass it up to the caller
uh, yeah. this is a really confusing example. I guess in the original code, it relied on the assumption that it was going to wait for the dialog before processing this.

2022-04-21 22:49 UTC, sujeffreyl commented on SIL.Core/Reporting/ErrorReport.cs
>  		void ReportNonFatalException(Exception exception, IRepeatNoticePolicy policy);
Well, currently (the one I envision it) this is not only called if there are multiple things the user might do in response to the problem.  It's the only NotifyUserOfProblem thing in the interface, every overload goes through it eventually.

Even if there were multiple calls, I'm in favor of (but not married to) leaving that to the caller, rather than trying to presume on it.
Maybe you wouldn't want it to always appear if you'd generate the same minor warning thing 20+ times within a minute.

2022-04-21 22:51 UTC, sujeffreyl commented on SIL.Core/Reporting/ErrorReport.cs
>  		void ReportNonFatalExceptionWithMessage(Exception error, string message, params object[] args);
I'm not sure what this comment is for. Github shows it to me as belonging to ErrorReport.cs, about the interface, but the interface has no concrete implementation so the question of whether or not it will return until the user clicks a button doesn't make sense. Could you clarify what this is about?

2022-04-21 22:56 UTC, sujeffreyl commented on SIL.Core/Reporting/ErrorReport.cs
>  		void ReportNonFatalMessageWithStackTrace(string message, params object[] args);
I believe I am declaring it as an event?  Line 81 of WinFormsErrorReporter. I do attempt to push an event to the handler. I hope this all works. My thought is that all this button handling stuff is very analogous to click (or other events) of a Javascript / HTML page, so that's why my thought was to try to use EventHandller.
My next thing if that didn't work was I was thinking to do a Func<string>.
I'm not sure what good the bool parameter would do. The calling code that declares the handler/func doesn't have access to the diaog. How could it close it?

(Of course, I haven't really tested this yet... it seems like it'll be a bit of setup for me to drive a test to exercise all this code).

2022-04-21 22:57 UTC, sujeffreyl commented on SIL.Core.Desktop/IO/FileUtils.cs
> +			// TODO: Customizing of the 1st button is not implemented yet, don't check in until you deal with this.
good catch, will update

2022-04-21 23:03 UTC, sujeffreyl commented on SIL.Core/Reporting/ErrorReport.cs
> +		void NotifyUserOfProblem(IRepeatNoticePolicy policy, Exception error, string message, string[] actionLabels, EventHandler<string> selectionHandler);
I'm using "button texts" and "action labels" as mostly synonymous. (Except "button texts" isn't very proper if the IErrorReporter doesn't show any buttons).
I was thinking if the caller provided localized labels, then the handler would likewise switch on the localized texts. The actionLabels array and the handler should probably be created in the same function, so both should have access to the localized labels I'm envisioning.

Maybe the concern is brought up because you see hard-coded "Details" in Overload 4's handler, but 1) it was already hard-coded to the English text, and 2) they reference the same variable (actually constant right now), so that both will reference the same value, whether that is the English text always as it is right now or the potentially localized value if some great improvement were made to it.

2022-04-26 15:27 UTC, sujeffreyl commented
Decided to go with a different approach.

2022-04-26 15:27 UTC, closed without merging